### ISSUE TITLE
NoReverseMatch u'admin' is not a registered namespace

### ISSUE THREAD

**Issue by rozebud** [fangli/django-saml2-auth#1]
Hi Fang,
 I was excited to find your github for Okta w/ django. I ran into an issue though.

> NoReverseMatch at /accounts/login/
u'admin' is not a registered namespace
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/login/
Django Version:	1.9.5
Exception Type:	NoReverseMatch
Exception Value:	
u'admin' is not a registered namespace
Exception Location:	/Users/mrose/Dropbox/dev/samlauth/venv/lib/python2.7/site-packages/django/core/urlresolvers.py in reverse, line 596
Python Executable:	/Users/mrose/Dropbox/dev/samlauth/venv/bin/python
Python Version:	2.7.10

>/Users/mrose/Dropbox/dev/samlauth/venv/lib/python2.7/site-packages/django_saml2_auth/views.py in signin
    next_url = r.GET.get('next', reverse('admin:index')) 

>def signin(r):
    import urlparse
    from urllib import unquote
    next_url = r.GET.get('next', reverse('admin:index')) ...
    try:
        if "next=" in unquote(next_url):
            next_url = urlparse.parse_qs(urlparse.urlparse(unquote(next_url)).query)['next'][0]
    except:
        next_url = r.GET.get('next', reverse('admin:index'))

So i tried adding 'namespace="admin"' to the urlpatterns.
>urlpatterns = [
	url(r'^saml2_auth/', include('django_saml2_auth.urls', namespace="admin")),`

However, i then received the following error.

>Django Version:	1.9.5
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location:	/Users/mrose/Dropbox/dev/samlauth/venv/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 508

Do you know what I'm doing wrong? Thanks for your help!!

**Comment by fangli** [comment]
Hi, this plugin assume that you have the django built-in admin app enabled. (actually it was enabled by default)

Could you please open
http://127.0.0.1:8000/admin/login/ and post the result?

Could you please post your urls.py? just don't forget to hide sensitive information.

**Comment by fangli** [comment]
Did you figured it out? I'll close this issue. open a new one if you want.

**Comment by rozebud** [comment]
sorry for the late reply, I didn't have notification in githhub enabled. Yes, enable 'admin' got me past this issue. However, I have a new issue. I'll create a new issue as this one is closed.
