### ISSUE TITLE
Support for Django 1.10

### ISSUE THREAD

**Issue by tobias-9** [fangli/django-saml2-auth#11]
Several deprecation warnings appear when running with Django 1.9, as shown below, which need to be handled in order to support Django 1.10.

/.../lib/python3.4/site-packages/django_saml2_auth/urls.py:8: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got acs). Pass the callable instead.
  url(r'^acs/$', "acs", name="acs"),

/.../lib/python3.4/site-packages/django_saml2_auth/urls.py:9: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got welcome). Pass the callable instead.
  url(r'^welcome/$', "welcome", name="welcome"),

/.../lib/python3.4/site-packages/django_saml2_auth/urls.py:10: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got denied). Pass the callable instead.
  url(r'^denied/$', "denied", name="denied"),

/.../lib/python3.4/site-packages/django_saml2_auth/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^denied/$', "denied", name="denied"),

**Comment by tobias-9** [comment]
Looks like the Pull Request from @hzy will take care of this issue.

**Comment by fangli** [comment]
Yes I'll consider it. my concern is that PR dropped the support for old django versions.
I hope I can get a chance to fix and merge it soon. but before that, you may want to use that fork as a workaround.

**Comment by ayr-ton** [comment]
@fangli I can't see the PR 😢

**Comment by ayr-ton** [comment]
I can see a PR from September 2016. Is this will be merged?

**Comment by fangli** [comment]
@ayr-ton Merged and added support for django1.10. Please use django-saml2-auth==2.x.x for django >= 1.10.
