### ISSUE TITLE
Infinite Redirect Loop on Login with Microsoft ADFS

### ISSUE THREAD

**Issue by mwoodward-atd** [fangli/django-saml2-auth#115]
Since I'm totally new to all of this I'm sure this is a configuration issue of some sort I'm just missing, but when I hit my Django app with django-saml2-auth in the mix it successfully redirects me to the federated login page. After providing valid credentials, however, the app then goes into a loop where it's just flipping back and forth between my `ENTITY_ID` URL (which is https://myapp/saml2_auth/acs/) and a URL on the ADFS server with continually changing `SAMLRequest` values as a URL parameter.

The only clue I have to go on at this point is when I check my browser history, eventually one of the page titles for all this activity in the history is "SigVer Error" but after some cursory googling I'm not sure what that might mean. I saw some references to disabling signed responses at the pysaml2 level but didn't want to go too far with that without first trying to figure out if that's even the issue given the behavior I'm seeing.

Any ideas? I can share my settings if that'd be helpful but the only optional setting I'm adding is the `ENTITY_ID` value since my understanding is that it's required by ADFS.

Debugging is also a bit of a challenge since at this point even with the Django debug level set to DEBUG it isn't revealing much, so if there's debugging tips those would be much appreciated.

Thanks for any advice anyone can provide!

**Comment by mwoodward-atd** [comment]
Never mind, my bad with some django-stronghold configuration. :-)

**Comment by craigsander** [comment]
@mwoodward-atd - Experiencing same issue with stronghold. What was the configuration problem?

**Comment by mwoodward-atd** [comment]
@craigsander Sorry for this slipping through the cracks on my side -- looking at the configuration we have working now and recollecting what I think I had to add, I think it's these three patterns that did the trick:
`r'^/accounts/login/(.+)?$',`
`r'^/accounts/logout/(.+)?$',`
`r'^/saml2_auth/(.+)?$',`
