### ISSUE TITLE
Saml2 metadata file?

### ISSUE THREAD

**Issue by pconesa** [fangli/django-saml2-auth#12]
More than an issue, this is a question.
I need to implement SAML2 in my django app.

I want it to make it work with http://www.testshib.org

At http://www.testshib.org/register.html they are requesting a Metadata file I believe all Saml service providers must have. But in the documentation, unless I've missed it, I haven't seen anything. The METADATA_AUTO_CONF_URL doesn't seem to be an option in my case. I guess since it is required, there's nothing to do?.

**Comment by fangli** [comment]
I'm not pretty sure about testshib, usually we get the metadata from provider instead of providing one to them.

**Comment by jameelgrand** [comment]
I am using pingone sso for saml2   there is no metadata URL  , we will get metadata file ,   how to configure with that file instead of metadata url

**Comment by toloco** [comment]
Try to use something like this:

```
SAML2_AUTH = {
    'METADATA_AUTO_CONF_URL': 'file://{}/saml2/metadata.xml'.format(BASE_DIR)
}
```

**Comment by askvictor** [comment]
@toloco I've just tried that approach, but it doesn't work on account of the requests library not knowing how to handle the file:// schema
