### ISSUE TITLE
Database Default

### ISSUE THREAD

**Issue by hooman96** [fangli/django-saml2-auth#124]
Does the extention point to the default database inside django settings.py or can we specify the database and its entry point?

**Comment by umbrella-yaroslav-graboveckiy** [comment]
It's working with Django models, so I assume that, yes, it's using default DB connection.

**Comment by Olshansk** [comment]
Yes, we confirmed that it is the default connection unless there is a router that says otherwise.

The solution to our problem can be found here: https://stackoverflow.com/questions/58866132/django-multiple-databases-connections
