### ISSUE TITLE
user_identity dict is empty

### ISSUE THREAD

**Issue by Olshansk** [fangli/django-saml2-auth#126]
[This line](https://github.com/fangli/django-saml2-auth/blob/825c1092803c38f626089763a7a3e030f2f82c1d/django_saml2_auth/views.py#L170) in the code keeps returning an empty dict (not a None).

I've confirmed that I have a username, name, email in my okta account.

I've confirmed that my `ATTRIBUTES_MAP` map is correct (though that doesn't matter because my dict is empty anyhow).

My hunch is that the scope being passed into the SAML client is incorrect or insufficient, but I'm kind of at a loss of what to try next.

Would appreciate any help!

**Comment by Olshansk** [comment]
@fangli Sorry for the direct ping, but do you have any suggestions regarding an avenue I can explore?

**Comment by kuzmoyev** [comment]
Experiencing the same issue. Have you found the solution yet?

**Comment by firstcloudconsulting** [comment]
Just modify django_saml2_auth/views.py (acs method) and print out the user_identity dictionary after the line, "user_identity = authn_response.get_identity()". Then you can see exactly what keys you have available for the mapping.

**Comment by Olshansk** [comment]
I should resolve this.

What @firstcloudconsulting is suggesting is exactly what I did. Everything worked but the map was empty. Turns out the server wasn't configured to return the data we needed.

**Comment by shakthifuture** [comment]
@firstcloudconsulting / @Olshansk , I am able to print the value. Can you someone tell me, how to get the value from package?
