### ISSUE TITLE
open redirect vulnerability

### ISSUE THREAD

**Issue by qwrrty** [fangli/django-saml2-auth#16]
We discovered recently while experimenting that a site using django-saml2-auth to authenticate against Okta is vulnerable to an [open redirect vulnerability](https://blog.qualys.com/securitylabs/2016/01/07/open-redirection-a-simple-vulnerability-threatens-your-web-applications). For example, a maliciously crafted URL like `https://safe.site/accounts/login_okta?next=//evil.site` will redirect the user to Okta for authentication, which will then redirect them to `evil.site` after they successfully authenticate. The evil site operator can then engage in a phishing attack, or even take advantage of the user's `safe.site` credentials to compromise the original site.

PR #17 was filed to address this issue.

**Comment by fangli** [comment]
Merged, thanks for your PR.
