### ISSUE TITLE
NoReverseMatch

### ISSUE THREAD

**Issue by rozebud** [fangli/django-saml2-auth#3]
> Request Method:	GET
> Request URL:	http://127.0.0.1:8000/saml_auth2/acs/acs/
> Django Version:	1.9.5
> Exception Type:	**NoReverseMatch**
> Exception Value:	
> **Reverse for 'acs' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []**

From this file:

> .../venv/lib/python2.7/site-packages/django_saml2_auth-1.0.4-py2.7.egg/django_saml2_auth/views.py in _get_saml_client

```
    return '{scheme}://{host}'.format(
        scheme=r.scheme,
        host=r.get_host(),
    )
def _get_saml_client(domain):
    acs_url = domain + reverse('acs') ...
    import tempfile
    tmp = tempfile.NamedTemporaryFile()
    f = open(tmp.name, 'w')
    f.write(urllib2.urlopen(settings.SAML2_AUTH['METADATA_AUTO_CONF_URL']).read())
    f.close()
    saml_settings = {
```

my urls.py file:
```
urlpatterns = [

    # These are the SAML2 related URLs. You can change "^saml2_auth/" regex to
    # any path you want, like "^sso_auth/", "^sso_login/", etc. (required)
    url(r'^saml_auth2/acs/', include('django_saml2_auth.urls')),

    # The following line will replace the default user login with SAML2 (optional)
    url(r'^accounts/login/$', 'django_saml2_auth.views.signin'),

    # The following line will replace the admin login with SAML2 (optional)
    url(r'^admin/login/$', 'django_saml2_auth.views.signin'),

    # google chrome favicon fix
    url(r'^favicon.ico/$', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'img/favicon.ico')),
    url(r'^$', RedirectView.as_view(url='outage')),
    url(r'^admin/', admin.site.urls),
    url(r'^manage/', admin.site.urls),
    url(r'^outage/', include('comapp.urls')),
```

I'm not entirely sure where the problem is, so I don't know what files I should post to help troubleshoot.

**Comment by fangli** [comment]
Hi @rozebud I just fixed this issue and released a new version.
Please do
pip install django-saml2-auth --upgrade
and try the new release.

**Comment by fangli** [comment]
Please let me know if it's fixed.

**Comment by rozebud** [comment]
HI @fangli, I know get the following error:

> Exception at /admin/login/
We got a URL reverse issue: ['admin:index']. This is a known issue but please still submit a ticket at https://github.com/fangli/django-saml2-auth/issues/new
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/login/
Django Version:	1.9.5
Exception Type:	Exception
Exception Value:	
We got a URL reverse issue: ['admin:index']. This is a known issue but please still submit a ticket at https://github.com/fangli/django-saml2-auth/issues/new
Exception Location:	/Users/mrose/Dropbox/dev/comnotify/venv/lib/python2.7/site-packages/django_saml2_auth/views.py in get_reverse, line 55
Python Executable:	/Users/mrose/Dropbox/dev/comnotify/venv/bin/python
Python Version:	2.7.10

**Comment by fangli** [comment]
@rozebud this plugin assumed that you have admin module installed or you will get such error.

**Comment by ghost** [comment]
@fangli , does the module still expecting admin?
