### ISSUE TITLE
G-Suite Error 400

### ISSUE THREAD

**Issue by justinforlenza** [fangli/django-saml2-auth#32]
When using G-Suite as Identity provider, i get the following 400 error:

`Error parsing the request, invalid_sp_id: The <Issuer> element MUST be present in <AuthnRequest> element.`

**Comment by toidi** [comment]
confirm the issue

**Comment by f1nality** [comment]
Same here
@justinforlenza @toidi have you managed to solve it?

**Comment by f1nality** [comment]
Looks like ENTITY_ID in settings.py is required
