### ISSUE TITLE
 can't access http://your-domain/saml2_auth/acs/

### ISSUE THREAD

**Issue by leslie971** [fangli/django-saml2-auth#46]
Hello
when i try to accede to this url    "http://your-domain/saml2_auth/acs/"   I am redirected to ... auth / denied /
"Sorry, you are not allowed to access this app"

SSO managed by Renater

Thanks

**Comment by leslie971** [comment]
django_saml2_auth 1.1.4

**Comment by fangli** [comment]
Please post your settings. please note CREATE_USER must be True if you want to create this user in system automatically.

**Comment by nils2504** [comment]
I have the same issue: 
`SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_AUTO_CONF_URL': 'https://xxxx.xxxx.com/FederationMetadata/2007-06/FederationMetadata.xml',

    # Optional settings below
    'DEFAULT_NEXT_URL': '/core',
    'CREATE_USER': True,
    'NEW_USER_PROFILE': {
        'USER_GROUPS': ["user"],  # The default group name when a new user logs in
        'ACTIVE_STATUS': True,  # The default active status for new users
        'STAFF_STATUS': False,  # The staff status for new users
        'SUPERUSER_STATUS': False,  # The superuser status for new users
    },
    'ATTRIBUTES_MAP': {
        'email': 'Email',
        'username': 'UserName',
        'first_name': 'FirstName',
        'last_name': 'LastName',
    },
    'ASSERTION_URL': MY_URL,
    'ENTITY_ID': '%s/saml2_auth/acs/' % MY_URL
}
`

**Comment by firstcloudconsulting** [comment]
I receive the same ("mysite.com" and "authprovider.com" are of course populated with actual hostnames):

```
# SAML2 Authentication
# https://github.com/fangli/django-saml2-auth
SAML2_AUTH = {
    # Metadata is required, choose either remote url or local file path
    'METADATA_AUTO_CONF_URL': 'https://authprovider.com/oamfed/idp/metadata',

    # Optional settings below
    'DEFAULT_NEXT_URL': '/admin',  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
    'CREATE_USER': 'TRUE', # Create a new Django user when a new user logs in. Defaults to True.
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],  # The default group name when a new user logs in
        'ACTIVE_STATUS': True,  # The default active status for new users
        'STAFF_STATUS': True,  # The staff status for new users
        'SUPERUSER_STATUS': False,  # The superuser status for new users
    },
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'email': 'Email',
        'username': 'UserName',
        'first_name': 'FirstName',
        'last_name': 'LastName',
    },
    'TRIGGER': {
        'CREATE_USER': 'myapp.utils.inspect_saml2_user',
        'BEFORE_LOGIN': 'myapp.utils.inspect_saml2_user',
    },
    'ASSERTION_URL': 'https://mysite.com', # Custom URL to validate incoming SAML requests against
    'ENTITY_ID': 'https://mysite.com/saml2_auth/acs/', # Populates the Issuer element in authn request
    'NAME_ID_FORMAT': 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient', # Sets the Format property of authn NameIDPolicy element
}
```

1. When I go to https://mysite.com/admin/, I am immediately redirected to https://authprovider.com/oam/pages/servererror.jsp
2. If I attempt to access https://mysite.com/saml2_auth/acs/ directly, I receive an error: "Sorry, you are not allowed to access this app | To report a problem with your access please contact your system administrator"
