### ISSUE TITLE
Internal Server Error KeyError: 

### ISSUE THREAD

**Issue by mcoti** [fangli/django-saml2-auth#49]
Hello i try to use  this plugin with okta, when run my app i get the followin error 
Internal Server Error: /saml2_auth/acs/
KeyError: 'Email'

**Comment by slashvortal** [comment]
Something related to this?!
https://github.com/fangli/django-saml2-auth/issues/52

**Comment by fangli** [comment]
I'll close this issue for inactive. raise another one if issue persistance.
