### ISSUE TITLE
add config for admin:index

### ISSUE THREAD

**Issue by tpeng** [fangli/django-saml2-auth#5]
Hey,

would it be a good idea to make default login page configurable through some setting? we have the scenario that to protect all the views with okta. it does not make sense to redirect to admin:login for all the views.

thanks,

**Comment by fangli** [comment]
Hi for the first time when a new user logged in, it will be redirect to a page using template django_saml2_auth/welcome.html, you can create this templates file manually and show a nice welcome page, or just redirect to another view by JavaScript redirecting. 

And you can add a parameter "next=/path/to/your_page" to login page as well. once the user get back from okta, it will be redirected to /path/to/your_page automatically.

**Comment by tpeng** [comment]
thanks, that works. closing issue.

**Comment by jameelgrand** [comment]
where I need to give next=/path/to/your_page    . I am confused please help
