### ISSUE TITLE
unable to work with windows

### ISSUE THREAD

**Issue by Bhanu414** [fangli/django-saml2-auth#59]
I'm using windows 10 but it give me missing `[xmlsec,xmlsec1]` 
I tried couple of ways
    - pip install`, 
    - downloaded zip file
but unable to install.

Is there any way to install that I'm not aware of?

**Comment by fangli** [comment]
This module uses pysaml2 as a dependency, which is really complicate and mass.
And, seems like xmlsec1 is not a pure python module.

So, please let me know if you have a workaround.
Life is tough though.

**Comment by vkbamania** [comment]
Do you guys find any solutions to this problem??
Really need it though...

**Comment by vkbamania** [comment]
> Do you guys find any solutions to this problem??
> Really need it though...

Okay found the solution 
1. Install Python-xmlsec from this link : [https://ci.appveyor.com/project/bgaifullin/python-xmlsec](https://ci.appveyor.com/project/bgaifullin/python-xmlsec
  )
2. Download and install Windows binaries for xmlsec from the following link:
[https://www.zlatkovic.com/pub/libxml/](https://www.zlatkovic.com/pub/libxml/)
 => add files to windows path and restart browser
