### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by jmaslanka** [fangli/django-saml2-auth#60]
Hello.

Some time ago I decided to use your package but I had to make a few changes. After forking and editing I realized the code isn't of a very high quality. Would you mind if I sent PR with some PEP8 changes and maybe other improvements?

**Comment by jmaslanka** [comment]
Just as I found some free time to do that I noticed @kronion already made some improvements. I don't want to make more mess so I'll just leave that to him. In case I find anything in the future I'll just send my PR.

**Comment by ayr-ton** [comment]
Ok, thanks. Closing the issue for now o/
