### ISSUE TITLE
SigverError: Can't find ['xmlsec1'] and metadata never fetched ?

### ISSUE THREAD

**Issue by kedare** [fangli/django-saml2-auth#63]
Hello.

I'm trying to setup SAML Authentication using a KeyCloak server, I've setup the django app like this :

```
SAML2_AUTH = {
    # Required setting
    'METADATA_AUTO_CONF_URL': 'https://xxx.xxx.net/auth/realms/xxx/protocol/saml/descriptor',
}
```

But so far

All the pages related to SAML (`/saml2_auth/...`, `/admin/login/`) are returning : 
```
SigverError at /admin/login/
Can't find ['xmlsec1']
```

And I don't see any incoming request fetching the SAML metadata

What could be the cause ?

Thanks

**Comment by kedare** [comment]
Looks like this was because I didn't install the required binrary, the error is not very explicit

**Comment by Skylude** [comment]
If on MacOSX brew install xmlsec1
