### ISSUE TITLE
DRF support?

### ISSUE THREAD

**Issue by JonasKs** [fangli/django-saml2-auth#74]
We're currently looking into implementing authentication on top of our API, where ADFS/SAML would be the cleanest solution. How ever, only certain user groups in AD should have access. 
Reading through the docs here, its not clear whether this package only support pure Django or also DRF?

**Comment by fangli** [comment]
Not sure what does DRF mean?

**Comment by JonasKs** [comment]
Django rest framework. 
I'm closing this issue, (Django Auth ADFS)[https://github.com/jobec/django-auth-adfs] solved my issue.
