### ISSUE TITLE
We got a URL reverse issue: ['admin:index']

### ISSUE THREAD

**Issue by kennyjohnson2** [fangli/django-saml2-auth#76]
I received this error when trying to integrate with Okta. I looked at other issues opened, and I do have the url(r'^saml2_auth/', include('django_saml2_auth.urls')), line at the top of my URL patterns, but still have the issue.

**Comment by kennyjohnson2** [comment]
this was solved by using git clone of the master branch instead of 2.2.0 through a pip install.

**Comment by phamj88** [comment]
shouldn't this be fixed then if the pip version is somehow bad?
