### ISSUE TITLE
ImportError: cannot import name patterns

### ISSUE THREAD

**Issue by ashishk1994** [fangli/django-saml2-auth#8]
I am using django 1.11 and getting import error,

`importError: cannot import name patterns`

Can someone please help me with this.

**Comment by magrif** [comment]
Your version of django very old. Try update it.

**Comment by martynasjocius** [comment]
Django 1.10 dropped support for URL patterns, django_saml2_auth now works only with Django <= 1.9 (and displays a warning "django.conf.urls.patterns() is deprecated and will be removed in Django 1.10"). Please update this package to support Django >= 1.10. Thanks!

**Comment by naggie** [comment]
I bet https://github.com/fangli/django-saml2-auth/pull/10 would fix it.

**Comment by fangli** [comment]
@naggie Fixed and merged. now use 2.x.x for django>=1.10
