### ISSUE TITLE
Logout does nothing with Okta

### ISSUE THREAD

**Issue by debnet** [fangli/django-saml2-auth#86]
When using dedicated logout, it does not disconnect from Okta account so when redirected it reconnects itself, logout is mostly useless. Is it a normal behaviour? All the best. ;)

**Comment by markvroling** [comment]
what you could do is doing a redirect to Okta after you logout the user from Django. Something like this:
```
from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_user(request):
    logout(request)
    return redirect({{your_okta_url}}/login/signout)
```

**Comment by debnet** [comment]
Why not. Does Okta provide a Single Signout form?

**Comment by fangli** [comment]
Basically SSO means you sign-in once, you signed in anywhere. that's by design.
But if you want to signout okta too, redirect the user to {{your_okta_url}}/login/signout.

**Comment by ambsw-technology** [comment]
We ran into the absence of SLO.  It looks like the SAML config includes an SLO URL.  Is there some reason we can't automatically grab it for redirection?
