### ISSUE TITLE
Disable or delete user when disabled on the other side

### ISSUE THREAD

**Issue by debnet** [fangli/django-saml2-auth#87]
Not sure if possible because the authentification process is handled by the third-party (Okta and so on), but is it possible to disable or delete used when rejected at logon? Is there a way to clean removed users from application? All the best. ;)

**Comment by markvroling** [comment]
what you could do is doing a redirect to Okta after you logout the user from Django. Something like this:
```
from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_user(request):
    logout(request)
    return redirect({{your_okta_url}}/login/signout)
```

**Comment by ambsw-technology** [comment]
By design, I don't think the SAML service provider can tell the difference between a bad password, not permitted for the application, and abandoning the login process (on the IdP side).

**Comment by fangli** [comment]
SAML itself has done nothing with this.
But for SSO providers like Okta, they provide some sync or callback features. when you revoke a user in okta, their server sends callback to your server, just like an event trigger.
I think this may help. just ask them for details.
